Prd hashicorp vault dev
travis-ci/travis-build pull request #2033
Opened 2022-07-06 10:15 UTC by makemp

2022-07-06 10:17 UTC, makemp commented on lib/travis/build/appliances/vault_connect.rb
> +          ENV['VAULT_ADDR'] = @vault[:api_url]
Is that you had on mind when you told me abbout setting VAULT_ADDR and VAULT_TOKEN variables or I just invoke `sh.export` here?

2022-07-06 13:07 UTC, vitalied requested changes

2022-07-06 13:07 UTC, vitalied commented on spec/fixtures/build_config_with_vault_kv2.json
> +}
new line at the end of file

2022-07-06 13:14 UTC, makemp commented on lib/travis/build/appliances/vault_connect.rb
> +          sh.terminate
That was I am asking:
https://github.com/travis-ci/travis-build/pull/2033#discussion_r914669848
Should I use export in shell or do this with ENV?
Once the builder did its job the instance is purged, right? so All ENV's are gone.
I just do not know the purposes of this VAULT_ADDR and VAULT_TOKEN, what do you plan to do with these afterwards so I do not know if I should leave it as it is now or export it into shell

2022-07-06 13:15 UTC, vitalied commented on spec/spec_helper.rb
> +WebMock.allow_net_connect!
@makemp why to allow net connections?

2022-07-06 17:45 UTC, makemp commented on lib/travis/services/vault/keys/resolver.rb
> +        def warn_message(path)
I can't move this to constant, as it has an argument (path)

2022-07-07 09:32 UTC, vitalied requested changes

2022-07-07 09:32 UTC, vitalied commented on lib/travis/services/vault/keys/kv2.rb
> +          response.status == 200 ? JSON.parse(response.body).dig('data', 'data').to_json : nil
`JSON.parse(response.body).dig('data', 'data').to_json if response.status == 200`

2022-07-07 09:32 UTC, vitalied commented on lib/travis/services/vault/connect.rb
> +          headers: { 'X-Vault-Token' => vault[:token] }
`headers: { 'X-Vault-Token': vault[:token] }`

2022-07-07 09:32 UTC, vitalied commented on lib/travis/services/vault/keys/kv1.rb
> +            headers: { 'X-Vault-Token' => vault[:token] }
`headers: { 'X-Vault-Token': vault[:token] }`

2022-07-07 09:32 UTC, vitalied commented on lib/travis/services/vault/keys/kv2.rb
> +            headers: { 'X-Vault-Token' => vault[:token] }
`headers: { 'X-Vault-Token': vault[:token] }`

2022-07-07 09:32 UTC, vitalied commented on spec/build/services/vault/connect_spec.rb
> +          with(headers: { 'X-Vault-Token' => 'my-token' }).
`headers: { 'X-Vault-Token': 'my-token' }`
replace everywhere

2022-07-07 15:24 UTC, merged